### ISSUE TITLE
Enhancement: CLI command to check CWE memberships

### ISSUE THREAD

**Issue by lirantal** [OWASP/cwe-sdk-javascript#1]
Original issue from previous repo: https://github.com/lirantal/cwe-sdk/issues/2

---

**Is your feature request related to a problem? Please describe.**
Sometimes CWE is a member of other enumerations. It will be helpful to obtain the related categories in order to get the other weakness descriptions.

**Describe the solution you'd like**
For example, we run the command 
`> cwe-sdk memberships 778`
 and it will output "A10: 2017 Insufficient Logging & Monitoring". 
Here is CWE: https://cwe.mitre.org/data/definitions/778.html

**Comment by alemagio** [comment]
Hi
Can I work on this?

**Comment by lirantal** [comment]
For sure!

**Comment by alemagio** [comment]
@lirantal 
Ok, so, here is my idea to implement this:
- I found that in the cwe-archive file some weaknesses have a field called `Has_Member` which may contain some other weaknesses (this is, I think) what we are looking for.
- my idea is to add this information like we already did for the `ChildOf` property in the build step.

What do you think?

**Comment by lirantal** [comment]
@alemagio yep, that sounds right. Looks like it should actually return 2 memberships: 
![image](https://user-images.githubusercontent.com/316371/98812531-5862dd80-242b-11eb-9196-ba3bbca711c4.png)

We should make sure we work with arrays here incase there is indeed more than one.
Does that sound ok?
