### ISSUE TITLE
Enhancement: download latest XML version as part of the build

### ISSUE THREAD

**Issue by lirantal** [OWASP/cwe-sdk-javascript#2]
**Is your feature request related to a problem? Please describe.**

Right now we have to manually download the latest version of the XML file and put it in the build assets.

**Describe the solution you'd like**

I requested from the CWE CAPSEC team that there will be an alias to the latest version and they agreed, and it's now available at https://cwe.mitre.org/data/xml/cwec_latest.xml.zip allowing to download this one in particular in every build.

**Comment by alemagio** [comment]
Hi, I'm thinking about working on this if still available.
The idea is basically to add a postintall script to download and unpkg that file and use its content to replace what's inside the `raw` directory correct?

**Comment by lirantal** [comment]
Yes, definitely available!

Almost that! It should exist as a prebuild or some other hook or build configuration so that when we push the package it is already bundled inside (Just to clarify, what you proposed is that upon install the consumer downloads it via the postinstall which I'd prefer to avoid and make it already available to the consumer with the package and no extra network calls or steps needed).

Happy to see this coming @alemagio ❤️

**Comment by alemagio** [comment]
Thanks for the explanation.
I'm on it, hopefully I'll push a draft this weekend.
