### ISSUE TITLE
IDEA: Pre-built CLI executables

### ISSUE THREAD

**Issue by lirantal** [OWASP/cwe-sdk-javascript#21]
Adding pre-built CLI executables so that end users don't need to have a local Node.js environment and don't need to depend on third-party dependency installs.

Recommendation: explore the use of `ncc` for that and build those artifacts as part of the release CI process.

**Comment by Mr-Unforgettable** [comment]
Can you assign me this? I want to give it a shot.

**Comment by 0xSaksham** [comment]
@lirantal Can I solve this issue as a part of Hacktoberfest 2023

**Comment by lirantal** [comment]
Sure @0xSaksham but do you want to first describe what do you intend to do as part of this ticket?
