### ISSUE TITLE
Enhancement: add badge to link to the OWASP project page

### ISSUE THREAD

**Issue by lirantal** [OWASP/cwe-sdk-javascript#3]
The OWASP project page is at https://owasp.org/www-project-cwe-toolkit/
Let's make it visible by adding a badge on the README

**Comment by alemagio** [comment]
I'm on it if no one else is working on it.

**Comment by alemagio** [comment]
Well, I opened a PR, I'll close it if necessary but saturday morning is my time to open source so couldn't wait :joy:
